---
- name: Create vmail group
  group:
    name: vmail
  notify: restart dovecot

- name: Create vmail user
  user:
    name: vmail
    group: vmail
    home: /home/vmail
    shell: /bin/sh
  notify: restart dovecot

- name: Add DeltaChat OBS repository key
  copy:
    src: obs-home-deltachat.gpg
    dest: /etc/apt/keyrings/obs-home-deltachat.gpg
    mode: '0444'
    owner: root
    group: root

- name: Add DeltaChat OBS repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/obs-home-deltachat.gpg] https://download.opensuse.org/repositories/home:/deltachat/Debian_12/ ./"
    state: present
    filename: deltachat
    update_cache: yes

- name: Install Dovecot packages
  apt:
    name: 
      - dovecot-imapd
      - dovecot-lmtpd
      - rsync
    state: present

- name: Configure Dovecot auth
  copy:
    src: auth.conf
    dest: /etc/dovecot/auth.conf
    mode: '0644'
    owner: root
    group: root
  notify: restart dovecot

- name: Configure Dovecot
  template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    mode: '0644'
  notify: restart dovecot

- name: Configure Dovecot push notification
  copy:
    src: push_notification.lua
    dest: /etc/dovecot/push_notification.lua
    mode: '0644'
    owner: root
    group: root
  notify: restart dovecot

- name: Configure expunge cron job
  template:
    src: expunge.cron.j2
    dest: /etc/cron.d/expunge
    mode: '0644'
    owner: root
    group: root 