---
- name: restart postfix-mta-sts-resolver
  service:
    name: postfix-mta-sts-resolver
    state: restarted
    enabled: yes

- name: restart postfix
  service:
    name: postfix
    state: restarted
    enabled: yes 