---
- name: Install Postfix packages
  apt:
    name:
      - postfix
      - postfix-mta-sts-resolver
    state: present

- name: Configure MTA-STS daemon
  copy:
    src: mta-sts-daemon.yml
    dest: /etc/mta-sts-daemon.yml
    mode: '0644'
    owner: root
    group: root
  notify: restart postfix-mta-sts-resolver

- name: Configure Postfix login map
  copy:
    src: login_map
    dest: /etc/postfix/login_map
    mode: '0644'
    owner: root
    group: root
  notify: restart postfix

- name: Configure Postfix submission header cleanup
  copy:
    src: submission_header_cleanup
    dest: /etc/postfix/submission_header_cleanup
    mode: '0644'
    owner: root
    group: root
  notify: restart postfix

- name: Configure Postfix main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    mode: '0644'
  notify: restart postfix

- name: Configure Postfix master.cf
  template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
    mode: '0644'
  notify: restart postfix

- name: Add postfix user to opendkim group
  user:
    name: postfix
    groups: opendkim
    append: yes
  notify: restart postfix 