---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name:
      - lowdown
      - qrencode
      - python3-pip
      - python3-virtualenv
    state: present

- name: Create apt keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Create base directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /var/www/src
    - /var/www/html
    - /usr/lib/cgi-bin 